apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-cacerts-job
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-cacerts-job
  chart:
    git: https://github.com/bilgesimens/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: store
      component_name: store-net
      namespace: store-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://vault.internal.machine:8200
      authpath: devstore-net-auth
      secretcryptoprefix: secretsv2/data/crypto/peerOrganizations/store-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/store-net/ca/store
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=US/ST=New York/L=New York/O=Store/CN=ca.store-net.minikube.network
