apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-peer0
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-peer0
  chart:
    git: https://github.com/bilgesimens/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: store-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.store-net:7051
      gossipexternalendpoint: peer0.store-net.svc.cluster.local:8443
      localmspid: storeMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: store-user

    storage:
      peer:
        storageclassname: storesc
        storagesize: 512Mi
      couchdb:
        storageclassname: storesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.machine:8200
      authpath: devstore-net-auth
      secretprefix: secret/data/crypto/peerOrganizations/store-net/peers/peer0.store-net
      secretambassador: secret/data/crypto/peerOrganizations/store-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/data/credentials/store-net/couchdb/store?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: svc.cluster.local

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
