apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-net-ca
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-net-ca
  chart:
    git: https://github.com/bilgesimens/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    deployment:
      annotations:
    annotations:  
      service:
      pvc:
    metadata:
      namespace: supplychain-net
      images:
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
        
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://vault.internal.machine:8200
      authpath: devsupplychain-net-auth
      secretcert: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
      secretkey: secretsv2/data/crypto/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
      secretadminpass: secretsv2/data/credentials/supplychain-net/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 443
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: svc.cluster.local
