apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-warehouse
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-warehouse
  chart:
    git: https://github.com/bilgesimens/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: warehouse-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.warehouse-net:7051
      localmspid: warehouseMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.machine:8200
      authpath: localwarehouse-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/warehouse-net/users/admin
      orderersecretprefix: secret/data/crypto/peerOrganizations/warehouse-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      Cr0CChgKFggCGgYIsumElwYiCmFsbGNoYW5uZWwSoAIKnQIKCmFsbGNoYW5uZWwSZRJjCgtBcHBs
      aWNhdGlvbhJUCAESUAoMd2FyZWhvdXNlTVNQEkAaBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dy
      aXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAGqcBEqQBCgtBcHBsaWNhdGlvbhKU
      AQgBEo8BCgx3YXJlaG91c2VNU1ASfwgBGjMKC0FuY2hvclBlZXJzEiQSGgoYChNwZWVyMC53YXJl
      aG91c2UtbmV0EIs3GgZBZG1pbnMaBwoDTVNQEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJz
      EgAiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAKgZBZG1pbnM=

