apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-cacerts-job
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-cacerts-job
  chart:
    git: https://github.com/bilgesimens/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: warehouse
      component_name: warehouse-net
      namespace: warehouse-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://vault.internal.machine:8200
      authpath: devwarehouse-net-auth
      secretcryptoprefix: secret/data/crypto/peerOrganizations/warehouse-net/ca
      secretcredentialsprefix: secret/data/credentials/warehouse-net/ca/warehouse
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=US/ST=Massachusetts/L=Boston/O=Warehouse/CN=ca.warehouse-net
